#
# Configure L3 between Core Router and Aggregate
#
# Network Engineering Tasks:
#  - L3 interface on Core, OSPF enabled
#  - L3 interface on Aggregate, OSPF enabled
#
# Note: MTU if specified must be done as a number, jumbo and default generates
#       Ansible errors.  https://github.com/CiscoDevNet/ansible-dcnm/issues/151

- hosts: dcnm
  gather_facts: false
  connection: ansible.netcommon.httpapi

  collections:
    - cisco.dcnm

  vars:
    # Need to extend timeouts because discovery process is slow
    ansible_command_timeout: 1800
    ansible_connect_timeout: 1800

    switch_username: "{{ lookup('env', 'SWITCH_USER') }}"
    switch_password: "{{ lookup('env', 'SWITCH_PASS') }}"

  tasks:
    - name: Create L3 Routed Link between Core and Aggregate
      dcnm_interface:
        fabric: "{{ site1.fabric_name }}"
        check_deploy: yes
        state: merged
        config:
          - name: Ethernet1/2
            deploy: yes
            switch:
              - "{{ site1.spine1_ip }}"
            type: eth
            profile:
              admin_state: yes
              mode: "routed"
              mtu: "9216"
              ipv4_addr: 192.168.0.1
              ipv4_mask_len: 30
              cmds:
                - ip router ospf 3155 area 0.0.0.0
          - name: Ethernet1/2
            switch:
              - "{{ site1.bgw1_ip }}"
            type: eth
            profile:
              admin_state: yes
              mode: "routed"
              mtu: "9216"
              ipv4_addr: 192.168.0.2
              ipv4_mask_len: 30
              cmds:
                - ip router ospf 3155 area 0.0.0.0
